FIrst pull request for Hello Microverse! Project
mateoburvi/hello-microverse pull request #1
Opened 2023-05-31 19:56 UTC by mateoburvi

### Hello Microverse! Proyect

In this first project, we learn how to configure repositories

- add linters to the project
- add the .gitignore file
- make some basic HTML and CSS code to test

2023-05-31 20:33 UTC, rica213 requested changes
# 🟡 STATUS: REQUIRED CHANGES ♻️ 
Hi Mateo (@mateoburvi )
My name is Larissa. I am your code reviewer 🤓

Congratulations on your hard work! 💪💪💪While the project is impressive, I have a few suggestions for enhancements that can further align it with our goals.📈
Kindly check all my comments below and if you have any questions don't hesitate to mention me in your comment 😺😺
Please keep up 🤗🤗
<img src="https://media3.giphy.com/media/3kAn3wmpeXcKV7ckJ8/giphy.gif"/>


## Highlights
Good use of .gitignore ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 20:33 UTC, rica213 commented on README.md
- [ ] Kindly do not remove all the headings from the [README file template](https://github.com/microverseinc/readme-template). 🙏🏽🙏🏽 You should customize it, based on your project. Note that complete documentation enhances user experience, encourages community engagement, establishes credibility, and contributes to the project's long-term success. 🤝🏾

2023-05-31 20:33 UTC, rica213 commented on .gitignore
Congratulations on your knowledge of using .gitignore!🥳🥳

- [ ] Please use the configuration of the Linters for the HTML/CSS module instead. We are not using Javascript yet, so that is the reason your Linters check fails 🫥
You can check the configuration [here](https://github.com/microverseinc/linters-config/tree/master/html-css)

2023-06-02 16:20 UTC, V-Blaze approved these changes
Hi @mateoburvi  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Linters setup correctly 💯
-  Meaningful commit messages👍
-  Correct Github flow🟢 👍

## Optional suggestions
- [OPTIONAL] For your future projects, when writing a commit message, always remember to capitalize the first letter of the commit message. :wave: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 16:20 UTC, V-Blaze commented on README.md
> +  <br/>
- [OPTIONAL] As part of customizing the README, you were meant to remove this logo here. This is just a placeholder. I'll suggest you remove this before proceeding to merge this pull request. :smile: :wave: 

- LOGO TO REMOVE:
![Screenshot from 2023-06-02 17-11-11](https://github.com/mateoburvi/hello-microverse/assets/107632780/b0414eca-1be0-407e-9456-314dc902da81)

2023-06-02 16:20 UTC, V-Blaze commented on README.md
> +  (change "myaccount" to your username in github)
- [OPTIONAL] You did great customizing the readme :+1: For this section, this an instruction on how to clone and use this your repository, so the user does not need to change his/her GitHub user name here, its your repo they are trying to clone. So ill suggest you remove `line 90` and change line 88 to `git clone https://github.com/mateoburvi/hello-microverse.git`. :+1: :smile:

2023-06-02 16:37 UTC, mateoburvi commented on README.md
> +  (change "myaccount" to your username in github)
Ok i was not sure about how that git clone link worked, thanks!

2023-06-02 16:37 UTC, merged